CREATE DATABASE IF NOT EXISTS music;

USE music;

CREATE TABLE IF NOT EXISTS songs (
  id INTEGER AUTO_INCREMENT,
  music_title VARCHAR(100) NOT NULL,
  music_url VARCHAR(250) NOT NULL,
  cover_art VARCHAR(250),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS artists (
  id INTEGER AUTO_INCREMENT,
  artist_name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS playlists (
  id INTEGER AUTO_INCREMENT,
  playlist_title VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS songsAndArtists (
  id INTEGER AUTO_INCREMENT,
  song_id INTEGER REFERENCES songs(id),
  artist_id INTEGER REFERENCES artists(id),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS playlistInformation (
  id INTEGER AUTO_INCREMENT,
  playlist_id INTEGER REFERENCES playlists(id),
  song_id INTEGER REFERENCES songs(id),
  PRIMARY KEY (id)
);